name = "bundle-builder"
client_id = "30d18de2120b2219f486cdac3972365d"
application_url = "https://bb-final1.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
scopes = "read_products,write_products,read_product_listings,read_collections,write_script_tags,read_script_tags,write_metafields,read_metafields,read_orders"

[auth]
redirect_urls = [
  "https://bb-final1.onrender.com/auth/callback",
  "https://bb-final1.onrender.com/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks"

[app_proxy]
url = "https://bb-final1.onrender.com/apps/bundle-builder"
subpath = "bundle-builder"
prefix = "apps"

[pos]
embedded = false
